# This is a basic workflow to help you get started with Actions

name: rebuild-readme

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '* 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       # Checkout repo
    - uses: actions/setup-python@v2   # Init python
      with:
        python-version: '3.x'
    - name: Cache                     # Try to cache python virt-env
      uses: actions/cache@v2.0.0
      with:
        path: ./env                                                           # A list of files, directories, and wildcard patterns to cache and restore
        key: ${{ runner.os }}-py-env-${{ hashFiles('**/requirements.txt') }}  # An explicit key for restoring and saving the cache
    - run: |-
        make rebuild-readme             # Create python virt-env + run script
        cat README.md                   
    - run: |-
        git diff
        git config --global user.email "readme-bot@petrroll.cz"
        git config --global user.name "README-bot"
        git diff --quiet || (git add README.md && git commit -m "Rebuild README")
        git push
